services:
  qr-generator:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: qr-generator
    restart: unless-stopped

    ports:
      - "0.0.0.0:18473:8080"

    cap_drop:
      - ALL

    security_opt:
      - no-new-privileges:true

    mem_limit: 128m
    cpus: "0.50"
    pids_limit: 50
